"""phase 3a: amazon SP-API integration

Revision ID: 52460350b9c9
Revises: c256e2878b3f
Create Date: 2026-07-13 04:30:41.202599
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "52460350b9c9"
down_revision = "c256e2878b3f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amazon_credentials",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("region", sa.Enum("NA", "EU", "FE", name="amazon_region"), nullable=False),
        sa.Column("marketplace_id", sa.String(length=50), nullable=False),
        sa.Column("seller_id", sa.String(length=50), nullable=False),
        sa.Column("lwa_client_id", sa.String(length=200), nullable=False),
        sa.Column("lwa_client_secret_encrypted", sa.Text(), nullable=False),
        sa.Column("lwa_refresh_token_encrypted", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_amazon_credentials_user_id"), "amazon_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "amazon_fba_shipments",
        sa.Column("credential_id", sa.UUID(), nullable=False),
        sa.Column("shipment_id", sa.String(length=50), nullable=False),
        sa.Column("shipment_name", sa.String(length=200), nullable=True),
        sa.Column("destination_fulfillment_center_id", sa.String(length=20), nullable=True),
        sa.Column("shipment_status", sa.String(length=30), nullable=False),
        sa.Column("label_prep_type", sa.String(length=30), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["credential_id"], ["amazon_credentials.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credential_id", "shipment_id", name="uq_amazon_fba_shipment"),
    )
    op.create_table(
        "amazon_financial_events",
        sa.Column("credential_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("amazon_order_id", sa.String(length=50), nullable=True),
        sa.Column("posted_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dedupe_key", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["credential_id"], ["amazon_credentials.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credential_id", "dedupe_key", name="uq_amazon_financial_event"),
    )
    op.create_index(
        "ix_amazon_financial_events_credential_posted",
        "amazon_financial_events",
        ["credential_id", "posted_date"],
        unique=False,
    )
    op.create_table(
        "amazon_inventory_snapshots",
        sa.Column("credential_id", sa.UUID(), nullable=False),
        sa.Column("asin", sa.String(length=20), nullable=True),
        sa.Column("fnsku", sa.String(length=20), nullable=True),
        sa.Column("seller_sku", sa.String(length=100), nullable=False),
        sa.Column("condition", sa.String(length=30), nullable=True),
        sa.Column("total_quantity", sa.Integer(), nullable=False),
        sa.Column("fulfillable_quantity", sa.Integer(), nullable=False),
        sa.Column("inbound_working_quantity", sa.Integer(), nullable=False),
        sa.Column("inbound_shipped_quantity", sa.Integer(), nullable=False),
        sa.Column("inbound_receiving_quantity", sa.Integer(), nullable=False),
        sa.Column("reserved_quantity", sa.Integer(), nullable=False),
        sa.Column("unfulfillable_quantity", sa.Integer(), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["credential_id"], ["amazon_credentials.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_amazon_inventory_credential_sku_time",
        "amazon_inventory_snapshots",
        ["credential_id", "seller_sku", "snapshot_at"],
        unique=False,
    )
    op.create_table(
        "amazon_orders",
        sa.Column("credential_id", sa.UUID(), nullable=False),
        sa.Column("amazon_order_id", sa.String(length=50), nullable=False),
        sa.Column("purchase_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_update_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("order_status", sa.String(length=30), nullable=False),
        sa.Column("fulfillment_channel", sa.String(length=10), nullable=True),
        sa.Column("sales_channel", sa.String(length=50), nullable=True),
        sa.Column("marketplace_id", sa.String(length=50), nullable=False),
        sa.Column("number_of_items_shipped", sa.Integer(), nullable=False),
        sa.Column("number_of_items_unshipped", sa.Integer(), nullable=False),
        sa.Column("order_total_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("order_total_currency", sa.String(length=10), nullable=True),
        sa.Column("is_business_order", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["credential_id"], ["amazon_credentials.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credential_id", "amazon_order_id", name="uq_amazon_order"),
    )
    op.create_index(
        "ix_amazon_orders_credential_purchase_date",
        "amazon_orders",
        ["credential_id", "purchase_date"],
        unique=False,
    )
    op.create_table(
        "amazon_sync_states",
        sa.Column("credential_id", sa.UUID(), nullable=False),
        sa.Column("resource", sa.String(length=50), nullable=False),
        sa.Column("next_token", sa.Text(), nullable=True),
        sa.Column("cursor_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status", sa.Enum("idle", "running", "error", name="amazon_sync_status"), nullable=False
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("records_last_sync", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["credential_id"], ["amazon_credentials.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credential_id", "resource", name="uq_amazon_sync_resource"),
    )
    op.create_table(
        "amazon_order_items",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("order_item_id", sa.String(length=50), nullable=False),
        sa.Column("asin", sa.String(length=20), nullable=True),
        sa.Column("seller_sku", sa.String(length=100), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("quantity_ordered", sa.Integer(), nullable=False),
        sa.Column("quantity_shipped", sa.Integer(), nullable=False),
        sa.Column("item_price_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("item_price_currency", sa.String(length=10), nullable=True),
        sa.Column("item_tax_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("promotion_discount_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["amazon_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", "order_item_id", name="uq_amazon_order_item"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("amazon_order_items")
    op.drop_table("amazon_sync_states")
    op.drop_index("ix_amazon_orders_credential_purchase_date", table_name="amazon_orders")
    op.drop_table("amazon_orders")
    op.drop_index(
        "ix_amazon_inventory_credential_sku_time", table_name="amazon_inventory_snapshots"
    )
    op.drop_table("amazon_inventory_snapshots")
    op.drop_index(
        "ix_amazon_financial_events_credential_posted", table_name="amazon_financial_events"
    )
    op.drop_table("amazon_financial_events")
    op.drop_table("amazon_fba_shipments")
    op.drop_index(op.f("ix_amazon_credentials_user_id"), table_name="amazon_credentials")
    op.drop_table("amazon_credentials")
    # ### end Alembic commands ###
    for enum_name in ("amazon_region", "amazon_sync_status"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
