"""phase 3a fast-follow: amazon listings

Revision ID: 8a921982e7ab
Revises: 52460350b9c9
Create Date: 2026-07-18 14:28:23.287429
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "8a921982e7ab"
down_revision = "52460350b9c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amazon_listings",
        sa.Column("credential_id", sa.UUID(), nullable=False),
        sa.Column("seller_sku", sa.String(length=100), nullable=False),
        sa.Column("asin", sa.String(length=20), nullable=True),
        sa.Column("product_type", sa.String(length=100), nullable=True),
        sa.Column("item_name", sa.String(length=500), nullable=True),
        sa.Column("condition_type", sa.String(length=30), nullable=True),
        sa.Column("status", postgresql.ARRAY(sa.String(length=30)), nullable=True),
        sa.Column("main_image_url", sa.String(length=1000), nullable=True),
        sa.Column("listing_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("listing_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["credential_id"], ["amazon_credentials.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credential_id", "seller_sku", name="uq_amazon_listing"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("amazon_listings")
    # ### end Alembic commands ###
